include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - web/**
    - tool/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - avoid_print
